INSERT INTO EXPENSE (AMOUNT, DESCRIPTION, DATE, CATEGORY, TAGS) VALUES
                                                                    (15.50, 'Coffee with a friend', '2024-03-15', 'FOOD', 'Social, Cafe'),
                                                                    (50.00, 'Groceries for the week', '2023-07-22', 'FOOD', 'Groceries, Home'),
                                                                    (120.00, 'New programming book', '2022-11-08', 'EDUCATION', 'Books, Tech'),
                                                                    (35.75, 'Public transport ticket', '2025-02-14', 'TRANSPORT', 'Commute'),
                                                                    (250.00, 'Dinner at a restaurant', '2023-12-31', 'FOOD', 'Dining, Social'),
                                                                    (12.99, 'Netflix subscription', '2024-01-10', 'ENTERTAINMENT', 'Streaming, Monthly'),
                                                                    (85.50, 'Electricity bill', '2022-05-17', 'UTILITIES', 'Monthly, Home'),
                                                                    (45.00, 'Gas for car', '2025-08-03', 'TRANSPORT', 'Fuel, Car'),
                                                                    (180.00, 'New winter jacket', '2022-12-20', 'SHOPPING', 'Clothing, Winter'),
                                                                    (65.00, 'Doctor visit copay', '2024-09-12', 'HEALTHCARE', 'Medical, Routine'),
                                                                    (28.75, 'Pizza delivery', '2023-04-07', 'FOOD', 'Delivery, Weekend'),
                                                                    (95.00, 'Internet bill', '2025-06-25', 'UTILITIES', 'Monthly, Internet'),
                                                                    (150.00, 'Concert tickets', '2024-08-18', 'ENTERTAINMENT', 'Music, Live'),
                                                                    (220.00, 'Flight booking', '2022-08-11', 'TRAVEL', 'Airfare, Vacation'),
                                                                    (32.50, 'Lunch at work cafeteria', '2025-01-28', 'FOOD', 'Work, Lunch'),
                                                                    (75.00, 'Dental cleaning', '2023-10-05', 'HEALTHCARE', 'Dental, Routine'),
                                                                    (18.99, 'Spotify premium', '2024-06-30', 'ENTERTAINMENT', 'Music, Subscription'),
                                                                    (200.00, 'Hotel for weekend trip', '2022-07-13', 'TRAVEL', 'Accommodation, Weekend'),
                                                                    (42.00, 'Uber ride to airport', '2025-04-09', 'TRANSPORT', 'Rideshare, Airport'),
                                                                    (89.99, 'New running shoes', '2023-02-26', 'SHOPPING', 'Sports, Health'),
                                                                    (15.00, 'Coffee and pastry', '2024-11-19', 'FOOD', 'Breakfast, Cafe'),
                                                                    (75.50, 'Groceries and household items', '2025-08-05', 'FOOD', 'Groceries, Weekly'),
                                                                    (125.00, 'Online course subscription', '2025-08-08', 'EDUCATION', 'Learning, Tech'),
                                                                    (22.75, 'Movie theater tickets', '2025-08-12', 'ENTERTAINMENT', 'Cinema, Date'),
                                                                    (155.00, 'Monthly gym membership', '2025-08-15', 'HEALTHCARE', 'Fitness, Monthly'),
                                                                    (89.99, 'Physics textbook for semester', '2025-08-10', 'EDUCATION', 'Books, University');