DROP TABLE IF EXISTS EXPENSE;

CREATE TABLE EXPENSE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(10,2) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DATE DATE NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    TAGS VARCHAR(255)
);